### ISSUE TITLE
Get rid of ES6 stuff

### ISSUE THREAD

**Issue by sushantdhiman** [Salakar/denque#4]
We would like to use `denque` in `node-mysql2`, but its currently using ES6 stuff which doesn't work with older Node versions.

Do you agree to remove ES6 stuff ? Library is pretty simple which I think can be converted to ES5 without much efforts

**Comment by Salakar** [comment]
An ES5 compatible version is now available (from v1.0.5 onwards):

```javascript
var denque require('denque/es5');

const denque = new Denque([1,2,3,4]);
denque.shift(); // 1
denque.pop(); // 4
```

**Comment by Salakar** [comment]
@sushantdhiman let me know if this is good enough for you.

**Comment by sushantdhiman** [comment]
@Salakar This should work :+1:

**Comment by Salakar** [comment]
@sushantdhiman added older node versions to this repo's travis config, https://travis-ci.org/Salakar/denque/builds/168292517

Tests all pass when using es5 version:
![image](https://cloud.githubusercontent.com/assets/5347038/19437289/a1d7cb22-946c-11e6-8054-849534fdf996.png)

**Comment by Salakar** [comment]
@sushantdhiman - Actually, fulling converting the whole project didn't take as long as I thought it would ;p v1.1.0 is now all ES5 from the default exports - so just require as normal now. Sorry!

https://travis-ci.org/Salakar/denque/builds/168297121

Closing issue.

**Comment by FallingSnow** [comment]
Doesn't let and const provide better performance than var?

**Comment by sushantdhiman** [comment]
@FallingSnow It entirely depends upon use case. `const` and `let` both are scope bound, using them in loops can be heavy. In general there is not much performance difference. Converting to `ES5` have opened this library for old node versions like `0.10`, I think thats more important because many env are still running on theses old node versions.

**Comment by Salakar** [comment]
@FallingSnow marginal and only in some cases better whilst in other cases its really bad, for example let compound assignments currently de-opt parent function in v8 environments.

But this change was done to allow old node support, nothing else. Performance stayed the same.
